route:
  group_by: ["alertname"]
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: "web.hook"
receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "https://webhook.site/fb680a3e-8be2-4f00-a410-4b0838380186"
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
